### ISSUE TITLE
Cellpond is cool, but it has bugs

### ISSUE THREAD

**Issue by 100xCode** [TodePond/CellPond#197]
Hey man, I really appreciate your [CellPond web app](https://cellpond.cool), but it really sucks that every time I try to zoom in or out, everything breaks. I understand that zooming out may confuse the application, but regardless, it does this weird thing where after zooming out or in then every time I try to add an element, it fills the screen instead. Please fix it. Thx! :v:

P.S. can you write a small readme about how to use the tool, because the stamp thing is absolutely confusing to me.

**Comment by TodePond** [comment]
Hi thanks for the bug report! Is there any chance you could take a screenshot of the zooming issue? Or describe how it breaks? That could help me to hunt it down :)

Also, I can write up a little guide later today to explain a bit more about stamps if you want :)

**Comment by TodePond** [comment]
So here's my explanation of stamps!
The first thing to understand is this: Some squares are **FIXED** and some are **DYNAMIC**.

**FIXED** squares always change a cell into the same colour, such as this one:
![image](https://user-images.githubusercontent.com/15892272/169523730-c7f99827-dfff-4a09-a8aa-cc33abc4a395.png)

**DYNAMIC** squares change a cell into various different colours, depending on the situation, such as this one:
![image](https://user-images.githubusercontent.com/15892272/169523945-9d116ac7-b201-44d1-9102-e0f476f5e43b.png)

If you put the _same_ dynamic square on both sides of a rule, then they _connect_.
For example, both of these DYNAMIC green squares are the SAME, so they get _connected_:
![image](https://user-images.githubusercontent.com/15892272/169524400-82003bb7-d9b1-445f-848e-c79d4694815b.png)

Because they are connected, the green cell on the right will always be set to the same colour as the green cell on the left (EVEN THOUGH it's dynamic). This helps you to move cells around more easily. For example, it allows us to combine the Rock + Sand + Water elements into one rule in [the video](https://youtu.be/sQYUQNozljo?t=253).

However... sometimes you might not want a dynamic cell to be connected. So you can put a stamp in it - and whatever cell you want it to be connected to instead.
Now, the green square on the right is connected to the black square on the left:
![image](https://user-images.githubusercontent.com/15892272/169525273-2d8a56a1-8424-4ad7-b9c0-c37d4af45ccc.png)

Or we could have it connected to NOTHING if we want:
![image](https://user-images.githubusercontent.com/15892272/169525397-19823997-4f91-4e4d-85a8-075e3bb17c24.png)

The examples above use a "range" of colours as the dynamic square. But other types of dynamic square work in similar way, such as a square with a diamond in it, or a group of joined squares.

**Comment by 100xCode** [comment]
Thanks man, very helpful. Also, could you make some kind of "not" shape so that I can have an eater element that does not eat air but eats everything else?

**Comment by TodePond** [comment]
That would be helpful! I've raised an issue to keep track of it: #198

**Comment by 100xCode** [comment]
> Hi thanks for the bug report! Is there any chance you could take a screenshot of the zooming issue? Or describe how it breaks? That could help me to hunt it down :)
> 
> Also, I can write up a little guide later today to explain a bit more about stamps if you want :)

The filling actually does not happen with zooming, it is an issue that I am unable to track down and understand how it happens. But, as already talked about with #186 I was experiencing an infinite falling sand issue where the sand would start teleporting from top to bottom over and over again. Also, to clarify, it seems like whenever the minicanvas is **re**loaded it starts glitching. I tried zooming in and then it glitched, but every time I zoomed out it started obeying the laws of my paddles. And then later when I was trying to make water the mouse randomly started painting giganto-pixels that didn't obey my laws and just stood there. I feel like I'm just at a complete loss here.

PS: one of the giganto pixels tried to act like water but idk anyway.

**Comment by TodePond** [comment]
Ok I think I know a few of the things going on.

Sand falling from top to bottom:
You can make the world 'wrap-around' by pressing the `=` key. Turn it back to normal by pressing `-`. This is a temporary feature until the controls menu is finished. More info in these issues:
#177 #11 

Gigantic pixels:
If you press a number key on the keyboard it changes the 'brush depth', which is useful for making fractals. This is also a placeholder until the controls menu is finished. More info:
#179 #11 

The glitching of the minicanvas - does it look like lots of little squares flickering in and out? If that's it, it's because the renderer + updater are still quite slow (I haven't done any optimisation yet) More info: https://github.com/TodePond/CellPond/issues?q=is%3Aopen+is%3Aissue+label%3Aperformance

**Comment by 100xCode** [comment]
Okay thanks. I don't understand why the giganto-pixels don't seem to obey my paddles, but the glitching thing was just from zooming in and out. And I thank you for adding that wrap-around feature, because I keep forgetting the this is **Cell**Pond and not **Sand**Pond and so you might want to make sure that cells won't get stuck at the edge of worlds or something. Gravity is not a given in CellPond and it is really meant for rules and does not cater for sand over anything else.
