### ISSUE TITLE
Clarity upon colors

### ISSUE THREAD

**Issue by 100xCode** [TodePond/CellPond#199]
# ?
I understand well that a horizontal rectangle is a color value. If placed in the red value of a square they become red and the same goes for other colors. *However*, diamonds are confusing. In your [CellPond video](youtu.be/sQYUQNozljo) (which I watched), you made a reed using the -1 for every event window thing in the green slot, but I don't understand how the diamond works. Where is it copying its color from? And why did the entire application break when I put a diamond in the -1 slot of a diamond?

Thanks,
100xCode

**Comment by TodePond** [comment]
> Where is it copying its color from?

It copies it from the cell that this cell is connected to. Remember my explanation for stamps? It's the same sort of thing :)
By default, it connects to the cell in that position. But you can make it connect to a different cell by using a stamp.

For example, in this rule... the square with a diamond in copies the green value of the blue cell.
![image](https://user-images.githubusercontent.com/15892272/169577194-5d4751ea-0f80-414b-b98f-24c7a20d3295.png)

But we can change this if we want! This one gets the green value of the red square instead, because we connect it with stamps.
![image](https://user-images.githubusercontent.com/15892272/169577303-558859d2-af85-4161-b4da-dc37dcb3dd45.png)

> And why did the entire application break when I put a diamond in the -1 slot of a diamond?

That's a bug because I was in a rush when I was finishing the video haha :D Here's the issue for it: #181

**Comment by 100xCode** [comment]
Thanks. Very helpful.
